# Generated by Django 4.2.4 on 2023-08-19 18:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='UZ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'user')], default=1),
        ),
    ]
